# Week 3 Assignment

In [1]:
import sqlite3
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 20)
pd.set_option('display.float_format', '{:,.2f}'.format)

conn = sqlite3.connect(':memory:')
cur = conn.cursor()
print("connected to sqlite")

connected to sqlite

## Loading the dataset

In [2]:
df = pd.read_csv('superstore.csv')
df.columns = [c.replace(' ', '_').replace('-', '_') for c in df.columns]

df.to_sql('superstore_raw', conn, if_exists='replace', index=False)

print(f"rows loaded: {len(df)}")
print(f"columns: {list(df.columns)}")

rows loaded: 9994
columns: ['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode', 'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State', 'Postal_Code', 'Region', 'Product_ID', 'Category', 'Sub_Category', 'Product_Name', 'Sales', 'Quantity', 'Discount', 'Profit']

In [ ]:

pd.read_sql("SELECT * FROM superstore_raw LIMIT 5", conn)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-214675,2020-12-05,2020-12-11,Second Class,CG-52508,Nancy Moore,Consumer,United States,Georgia City,...,63090,South,OFF-ENV-7527,Office Supplies,Envelopes,Poly String Tie Envelopes,23.26,6,0.50,2.51
1,2,CA-2020-771590,2020-01-15,2020-01-17,Same Day,CG-76321,Charles White,Consumer,United States,Virginia City,...,36972,East,TEC-COM-3612,Technology,Computers,Lenovo ThinkPad X1,"10,701.92",10,0.30,"2,323.72"
2,3,CA-2022-934674,2022-12-14,2022-12-21,Standard Class,CG-29790,Ashley Jackson,Home Office,United States,New York City,...,74157,East,OFF-ENV-4543,Office Supplies,Envelopes,Window Envelopes,35.33,6,0.00,0.64
3,4,CA-2022-725969,2022-08-03,2022-08-06,Same Day,CG-23740,Matthew Robinson,Consumer,United States,Virginia City,...,48986,East,OFF-BIN-1841,Office Supplies,Binders,Avery Heavy Duty Binder,37.65,6,0.40,10.02
4,5,CA-2022-804758,2022-04-25,2022-04-26,First Class,CG-50558,Margaret Brown,Consumer,United States,Pennsylvania City,...,60916,East,TEC-COM-3612,Technology,Computers,Lenovo ThinkPad X1,"3,037.81",2,0.00,-110.54

## Creating normalized tables

In [4]:
cur.executescript("""
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS orders;

CREATE TABLE customers (
    customer_id   TEXT PRIMARY KEY,
    customer_name TEXT,
    segment       TEXT,
    region        TEXT
);

CREATE TABLE products (
    product_id   TEXT PRIMARY KEY,
    product_name TEXT,
    category     TEXT,
    sub_category TEXT
);

CREATE TABLE orders (
    row_id      INTEGER PRIMARY KEY,
    order_id    TEXT,
    order_date  TEXT,
    ship_date   TEXT,
    ship_mode   TEXT,
    customer_id TEXT,
    product_id  TEXT,
    sales       REAL,
    quantity    INTEGER,
    discount    REAL,
    profit      REAL
);
""")
conn.commit()
print("tables created")

tables created

In [5]:
cur.executescript("""
INSERT OR IGNORE INTO customers
SELECT DISTINCT Customer_ID, Customer_Name, Segment, Region
FROM superstore_raw;

INSERT OR IGNORE INTO products
SELECT DISTINCT Product_ID, Product_Name, Category, Sub_Category
FROM superstore_raw;

INSERT OR IGNORE INTO orders
SELECT Row_ID, Order_ID, Order_Date, Ship_Date, Ship_Mode,
       Customer_ID, Product_ID, Sales, Quantity, Discount, Profit
FROM superstore_raw;
""")
conn.commit()

for t in ['customers', 'products', 'orders']:
    n = pd.read_sql(f"SELECT COUNT(*) as cnt FROM {t}", conn).iloc[0,0]
    print(f"{t}: {n:,} rows")

customers: 438 rows
products: 37 rows
orders: 9,994 rows

## Subqueries

### 1. Orders where sales are above average

In [6]:
query = """
SELECT
    o.order_id,
    c.customer_name,
    c.segment,
    p.category,
    ROUND(o.sales, 2) as sales,
    ROUND((SELECT AVG(sales) FROM orders), 2) as overall_avg
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN products p  ON o.product_id  = p.product_id
WHERE o.sales > (SELECT AVG(sales) FROM orders)
ORDER BY o.sales DESC
LIMIT 15
"""

result = pd.read_sql(query, conn)
print(f"orders above average: {pd.read_sql('SELECT COUNT(*) as n FROM orders WHERE sales > (SELECT AVG(sales) FROM orders)', conn).iloc[0,0]:,}")
result

orders above average: 3,102

,order_id,customer_name,segment,category,sales,overall_avg
0,CA-2022-170060,Jessica Robinson,Home Office,Technology,"24,770.60","2,124.11"
1,CA-2021-694655,Sandra Brown,Corporate,Technology,"24,131.58","2,124.11"
2,CA-2020-705173,Daniel Williams,Home Office,Technology,"24,048.12","2,124.11"
3,CA-2020-931882,Nancy Wilson,Corporate,Technology,"23,864.92","2,124.11"
4,CA-2022-343345,James Anderson,Consumer,Technology,"23,802.73","2,124.11"
5,CA-2021-351863,Patricia Martin,Home Office,Technology,"23,755.29","2,124.11"
6,CA-2022-440129,Patricia Davis,Home Office,Technology,"22,566.63","2,124.11"
7,CA-2019-334798,Jessica Brown,Consumer,Technology,"21,661.83","2,124.11"
8,CA-2019-187107,John Martinez,Home Office,Technology,"21,556.07","2,124.11"
9,CA-2022-683715,Matthew Williams,Consumer,Technology,"21,528.16","2,124.11"
10,CA-2022-103485,Richard Brown,Corporate,Technology,"21,325.11","2,124.11"
11,CA-2022-303263,James Moore,Home Office,Technology,"21,246.67","2,124.11"
12,CA-2020-681740,Michael Davis,Home Office,Technology,"21,107.13","2,124.11"
13,CA-2019-582862,Sandra Jones,Corporate,Technology,"20,773.29","2,124.11"
14,CA-2021-521457,Nancy Thompson,Consumer,Technology,"20,735.11","2,124.11"

### 2. Highest-value order line per customer

In [7]:
query = """
SELECT
    c.customer_name,
    c.segment,
    o.order_id,
    ROUND(o.sales, 2) as max_order_sales
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
WHERE o.sales = (
    SELECT MAX(o2.sales)
    FROM orders o2
    WHERE o2.customer_id = o.customer_id
)
ORDER BY max_order_sales DESC
LIMIT 15
"""

pd.read_sql(query, conn)

       customer_name      segment        order_id  max_order_sales
0   Jessica Robinson  Home Office  CA-2022-170060        24,770.60
1       Sandra Brown    Corporate  CA-2021-694655        24,131.58
2    Daniel Williams  Home Office  CA-2020-705173        24,048.12
3       Nancy Wilson    Corporate  CA-2020-931882        23,864.92
4     James Anderson     Consumer  CA-2022-343345        23,802.73
5    Patricia Martin  Home Office  CA-2021-351863        23,755.29
6     Patricia Davis  Home Office  CA-2022-440129        22,566.63
7      Jessica Brown     Consumer  CA-2019-334798        21,661.83
8      John Martinez  Home Office  CA-2019-187107        21,556.07
9   Matthew Williams     Consumer  CA-2022-683715        21,528.16
10     Richard Brown    Corporate  CA-2022-103485        21,325.11
11       James Moore  Home Office  CA-2022-303263        21,246.67
12     Michael Davis  Home Office  CA-2020-681740        21,107.13
13      Sandra Jones    Corporate  CA-2019-582862        20,773.29
14    Nancy Thompson     Consumer  CA-2021-521457        20,735.11

## CTEs (Common Table Expressions)

### 3. Total sales per customer

In [8]:
query = """
WITH customer_sales AS (
    SELECT
        o.customer_id,
        c.customer_name,
        c.segment,
        c.region,
        ROUND(SUM(o.sales), 2)  as total_sales,
        ROUND(SUM(o.profit), 2) as total_profit,
        COUNT(DISTINCT o.order_id) as num_orders
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY o.customer_id, c.customer_name, c.segment, c.region
)
SELECT *
FROM customer_sales
ORDER BY total_sales DESC
LIMIT 20
"""

pd.read_sql(query, conn)

,customer_id,customer_name,segment,region,total_sales,total_profit,num_orders
0,CG-53008,Daniel Williams,Home Office,West,"113,980.62","13,665.36",44
1,CG-40281,Christopher Moore,Consumer,East,"112,892.29","16,348.13",29
2,CG-88249,David Wilson,Consumer,West,"108,281.62","12,219.85",38
3,CG-40234,James Moore,Home Office,South,"107,263.24","13,903.30",27
4,CG-60229,Betty Jones,Corporate,South,"98,538.50","13,288.99",22
5,CG-16824,Matthew Wilson,Home Office,Central,"98,382.01","15,941.86",26
6,CG-55656,Robert Anderson,Home Office,East,"98,147.82","5,317.28",31
7,CG-44469,Sandra Thomas,Consumer,Central,"96,543.49","17,598.45",29
8,CG-43839,Daniel Jones,Home Office,Central,"94,316.32","12,271.18",36
9,CG-81359,Christopher Garcia,Corporate,West,"92,643.43","10,586.38",21
10,CG-39156,Nancy Anderson,Corporate,East,"92,255.79","13,372.38",30
11,CG-51561,Thomas Garcia,Home Office,Central,"92,218.34","15,753.34",30
12,CG-81072,David Taylor,Home Office,West,"91,520.64","8,888.62",28
13,CG-65546,Jennifer Jackson,Home Office,Central,"89,062.27","14,858.46",21
14,CG-48024,Nancy Harris,Home Office,Central,"86,695.50","10,396.74",27
15,CG-33336,Thomas Martin,Corporate,East,"86,518.40","7,086.40",29
16,CG-34866,Barbara Garcia,Consumer,South,"85,882.92","7,946.01",32
17,CG-86212,Jessica Johnson,Consumer,South,"85,818.43","12,596.17",34
18,CG-87728,Matthew Jones,Corporate,West,"85,159.76","12,851.79",24
19,CG-85594,Sandra Williams,Corporate,South,"84,442.86","5,398.25",30

### 4. Sales and profit by category

In [9]:
query = """
WITH cat_summary AS (
    SELECT
        p.category,
        p.sub_category,
        ROUND(SUM(o.sales),  2) as total_sales,
        ROUND(SUM(o.profit), 2) as total_profit,
        COUNT(*) as order_lines,
        ROUND(SUM(o.profit) * 100.0 / SUM(o.sales), 2) as margin_pct
    FROM orders o
    JOIN products p ON o.product_id = p.product_id
    GROUP BY p.category, p.sub_category
)
SELECT *
FROM cat_summary
ORDER BY total_profit DESC
"""

pd.read_sql(query, conn)

,category,sub_category,total_sales,total_profit,order_lines,margin_pct
0,Technology,Computers,"7,220,475.65","957,032.14",836,13.25
1,Technology,Phones,"3,569,666.04","468,053.34",832,13.11
2,Furniture,Tables,"3,515,800.52","407,838.74",796,11.60
3,Technology,Copiers,"2,019,367.07","261,284.61",833,12.94
4,Furniture,Chairs,"1,933,062.70","248,307.61",801,12.85
5,Furniture,Bookcases,"1,283,353.78","168,438.42",828,13.12
6,Technology,Machines,"933,495.88","125,062.66",856,13.40
7,Furniture,Furnishings,"298,254.59","37,939.37",875,12.72
8,Office Supplies,Storage,"199,195.30","26,826.45",397,13.47
9,Office Supplies,Accessories,"95,562.66","12,043.81",337,12.60
10,Office Supplies,Paper,"60,567.31","7,133.31",374,11.78
11,Office Supplies,Binders,"30,423.69","3,744.89",394,12.31
12,Office Supplies,Art,"23,139.42","3,053.50",336,13.20
13,Office Supplies,Envelopes,"15,485.59","1,940.67",356,12.53
14,Office Supplies,Labels,"13,652.25","1,777.14",375,13.02
15,Office Supplies,Supplies,"9,406.12","1,264.77",419,13.45
16,Office Supplies,Fasteners,"7,402.40",960.58,349,12.98

## Window Functions

### 5. ROW_NUMBER - ranking customers by total sales

In [10]:
query = """
WITH cust_totals AS (
    SELECT
        c.customer_name,
        c.segment,
        c.region,
        ROUND(SUM(o.sales), 2) as total_sales
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_id, c.customer_name, c.segment, c.region
)
SELECT
    ROW_NUMBER() OVER (ORDER BY total_sales DESC) as row_num,
    customer_name,
    segment,
    region,
    total_sales
FROM cust_totals
ORDER BY row_num
LIMIT 20
"""

pd.read_sql(query, conn)

    row_num       customer_name      segment   region  total_sales
0         1     Daniel Williams  Home Office     West   113,980.62
1         2   Christopher Moore     Consumer     East   112,892.29
2         3        David Wilson     Consumer     West   108,281.62
3         4         James Moore  Home Office    South   107,263.24
4         5         Betty Jones    Corporate    South    98,538.50
5         6      Matthew Wilson  Home Office  Central    98,382.01
6         7     Robert Anderson  Home Office     East    98,147.82
7         8       Sandra Thomas     Consumer  Central    96,543.49
8         9        Daniel Jones  Home Office  Central    94,316.32
9        10  Christopher Garcia    Corporate     West    92,643.43
10       11      Nancy Anderson    Corporate     East    92,255.79
11       12       Thomas Garcia  Home Office  Central    92,218.34
12       13        David Taylor  Home Office     West    91,520.64
13       14    Jennifer Jackson  Home Office  Central    89,062.27
14       15        Nancy Harris  Home Office  Central    86,695.50
15       16       Thomas Martin    Corporate     East    86,518.40
16       17      Barbara Garcia     Consumer    South    85,882.92
17       18     Jessica Johnson     Consumer    South    85,818.43
18       19       Matthew Jones    Corporate     West    85,159.76
19       20     Sandra Williams    Corporate    South    84,442.86

### 6. RANK within each segment

In [11]:
query = """
WITH cust_totals AS (
    SELECT
        c.customer_id,
        c.customer_name,
        c.segment,
        ROUND(SUM(o.sales), 2) as total_sales
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_id, c.customer_name, c.segment
)
SELECT
    segment,
    customer_name,
    total_sales,
    RANK()       OVER (PARTITION BY segment ORDER BY total_sales DESC) as rank_in_segment,
    DENSE_RANK() OVER (PARTITION BY segment ORDER BY total_sales DESC) as dense_rank
FROM cust_totals
ORDER BY segment, rank_in_segment
LIMIT 24
"""

pd.read_sql(query, conn)

     segment      customer_name  total_sales  rank_in_segment  dense_rank
0   Consumer  Christopher Moore   112,892.29                1           1
1   Consumer       David Wilson   108,281.62                2           2
2   Consumer      Sandra Thomas    96,543.49                3           3
3   Consumer     Barbara Garcia    85,882.92                4           4
4   Consumer    Jessica Johnson    85,818.43                5           5
5   Consumer   Matthew Williams    82,330.82                6           6
6   Consumer   Richard Martinez    77,887.08                7           7
7   Consumer       Susan Wilson    77,377.45                8           8
8   Consumer      Jessica Brown    76,694.79                9           9
9   Consumer      Charles White    75,955.06               10          10
10  Consumer    Robert Williams    73,092.27               11          11
11  Consumer        Mary Taylor    72,570.55               12          12
12  Consumer  Margaret Robinson    70,990.43               13          13
13  Consumer       Sarah Garcia    69,628.74               14          14
14  Consumer      Richard Moore    68,740.79               15          15
15  Consumer     Sarah Anderson    67,843.93               16          16
16  Consumer       Linda Taylor    67,710.41               17          17
17  Consumer      Karen Johnson    67,103.51               18          18
18  Consumer   Charles Thompson    66,951.24               19          19
19  Consumer     Margaret Brown    65,812.76               20          20
20  Consumer  Jennifer Robinson    65,186.05               21          21
21  Consumer    Ashley Martinez    64,640.42               22          22
22  Consumer     Richard Martin    62,575.92               23          23
23  Consumer     Anthony Taylor    62,111.15               24          24

### 7. Running total of sales per customer over time

In [12]:
query = """
WITH order_totals AS (
    SELECT
        o.customer_id,
        c.customer_name,
        o.order_date,
        ROUND(SUM(o.sales), 2) as daily_sales
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY o.customer_id, c.customer_name, o.order_date
),
top5 AS (
    SELECT customer_id
    FROM (
        SELECT customer_id, SUM(daily_sales) as ts
        FROM order_totals
        GROUP BY customer_id
        ORDER BY ts DESC
        LIMIT 5
    )
)
SELECT
    customer_name,
    order_date,
    daily_sales,
    ROUND(SUM(daily_sales) OVER (
        PARTITION BY customer_id
        ORDER BY order_date
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ), 2) as running_total
FROM order_totals
WHERE customer_id IN (SELECT customer_id FROM top5)
ORDER BY customer_name, order_date
LIMIT 30
"""

pd.read_sql(query, conn)

        customer_name  order_date  daily_sales  running_total
0         Betty Jones  2019-01-23     5,399.82       5,399.82
1         Betty Jones  2019-05-28     3,266.80       8,666.62
2         Betty Jones  2019-10-23     1,519.41      10,186.03
3         Betty Jones  2019-12-15       108.86      10,294.89
4         Betty Jones  2019-12-30       376.85      10,671.74
5         Betty Jones  2020-09-16     4,196.83      14,868.57
6         Betty Jones  2020-11-05       614.36      15,482.93
7         Betty Jones  2020-11-09     1,670.70      17,153.63
8         Betty Jones  2021-01-14     6,240.81      23,394.44
9         Betty Jones  2021-01-31       530.65      23,925.09
10        Betty Jones  2021-04-01    14,694.10      38,619.19
11        Betty Jones  2021-05-01       167.28      38,786.47
12        Betty Jones  2021-05-25       366.87      39,153.34
13        Betty Jones  2021-07-21     7,381.23      46,534.57
14        Betty Jones  2021-08-18     7,861.84      54,396.41
15        Betty Jones  2021-09-04    12,942.13      67,338.54
16        Betty Jones  2022-06-14     1,515.56      68,854.10
17        Betty Jones  2022-08-20        18.44      68,872.54
18        Betty Jones  2022-08-22     3,006.96      71,879.50
19        Betty Jones  2022-10-02     9,235.69      81,115.19
20        Betty Jones  2022-11-28     9,511.23      90,626.42
21        Betty Jones  2022-11-29     7,912.08      98,538.50
22  Christopher Moore  2019-01-20        26.67          26.67
23  Christopher Moore  2019-01-27    11,825.58      11,852.25
24  Christopher Moore  2019-04-08     9,305.60      21,157.85
25  Christopher Moore  2019-04-22       162.38      21,320.23
26  Christopher Moore  2019-06-14        41.02      21,361.25
27  Christopher Moore  2019-06-25     4,259.87      25,621.12
28  Christopher Moore  2019-11-24     8,037.67      33,658.79
29  Christopher Moore  2020-01-28     8,182.93      41,841.72

## Combining JOIN + CTE + Window Functions

### 8. Final customer summary with rankings

In [13]:
query = """
WITH customer_metrics AS (
    SELECT
        c.customer_id,
        c.customer_name,
        c.segment,
        c.region,
        COUNT(DISTINCT o.order_id)     as total_orders,
        ROUND(SUM(o.sales),  2)        as total_sales,
        ROUND(SUM(o.profit), 2)        as total_profit,
        ROUND(AVG(o.discount) * 100, 1) as avg_discount_pct,
        ROUND(SUM(o.profit) * 100.0 / SUM(o.sales), 2) as profit_margin_pct
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_id, c.customer_name, c.segment, c.region
)
SELECT
    RANK() OVER (ORDER BY total_sales DESC)  as sales_rank,
    customer_name,
    segment,
    region,
    total_orders,
    total_sales,
    total_profit,
    avg_discount_pct,
    profit_margin_pct,
    RANK() OVER (ORDER BY total_profit DESC) as profit_rank,
    DENSE_RANK() OVER (PARTITION BY segment ORDER BY total_sales DESC) as rank_in_segment
FROM customer_metrics
ORDER BY sales_rank
LIMIT 25
"""

pd.read_sql(query, conn)

,sales_rank,customer_name,segment,region,total_orders,total_sales,total_profit,avg_discount_pct,profit_margin_pct,profit_rank,rank_in_segment
0,1,Daniel Williams,Home Office,West,44,"113,980.62","13,665.36",18.20,11.99,19,1
1,2,Christopher Moore,Consumer,East,29,"112,892.29","16,348.13",15.50,14.48,2,1
2,3,David Wilson,Consumer,West,38,"108,281.62","12,219.85",17.40,11.29,36,2
3,4,James Moore,Home Office,South,27,"107,263.24","13,903.30",13.00,12.96,17,2
4,5,Betty Jones,Corporate,South,22,"98,538.50","13,288.99",19.60,13.49,22,1
5,6,Matthew Wilson,Home Office,Central,26,"98,382.01","15,941.86",19.60,16.20,4,3
6,7,Robert Anderson,Home Office,East,31,"98,147.82","5,317.28",12.90,5.42,236,4
7,8,Sandra Thomas,Consumer,Central,29,"96,543.49","17,598.45",15.90,18.23,1,3
8,9,Daniel Jones,Home Office,Central,36,"94,316.32","12,271.18",13.60,13.01,35,5
9,10,Christopher Garcia,Corporate,West,21,"92,643.43","10,586.38",13.80,11.43,58,2
10,11,Nancy Anderson,Corporate,East,30,"92,255.79","13,372.38",17.00,14.49,20,3
11,12,Thomas Garcia,Home Office,Central,30,"92,218.34","15,753.34",14.30,17.08,5,6
12,13,David Taylor,Home Office,West,28,"91,520.64","8,888.62",16.10,9.71,90,7
13,14,Jennifer Jackson,Home Office,Central,21,"89,062.27","14,858.46",15.50,16.68,7,8
14,15,Nancy Harris,Home Office,Central,27,"86,695.50","10,396.74",12.60,11.99,63,9
15,16,Thomas Martin,Corporate,East,29,"86,518.40","7,086.40",16.90,8.19,154,4
16,17,Barbara Garcia,Consumer,South,32,"85,882.92","7,946.01",18.20,9.25,122,4
17,18,Jessica Johnson,Consumer,South,34,"85,818.43","12,596.17",20.60,14.68,28,5
18,19,Matthew Jones,Corporate,West,24,"85,159.76","12,851.79",12.50,15.09,23,5
19,20,Sandra Williams,Corporate,South,30,"84,442.86","5,398.25",16.30,6.39,233,6
20,21,Susan Smith,Corporate,East,25,"84,099.55","11,740.38",12.00,13.96,40,7
21,22,Joseph Williams,Home Office,East,25,"84,079.48","10,680.88",15.60,12.70,55,10
22,23,Richard Brown,Corporate,East,28,"83,458.99","14,378.11",13.80,17.23,11,8
23,24,Jessica Davis,Corporate,South,29,"82,583.10","14,717.92",14.50,17.82,9,9
24,25,Matthew Williams,Consumer,South,26,"82,330.82","14,385.59",10.40,17.47,10,6

## Business Queries

### BQ1 - Top 10 customers by revenue

In [14]:
query = """
WITH cust_rev AS (
    SELECT
        c.customer_name,
        c.segment,
        c.region,
        ROUND(SUM(o.sales),  2) as revenue,
        ROUND(SUM(o.profit), 2) as profit
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_id
)
SELECT
    ROW_NUMBER() OVER (ORDER BY revenue DESC) as rank,
    customer_name, segment, region, revenue, profit
FROM cust_rev
ORDER BY revenue DESC
LIMIT 10
"""

pd.read_sql(query, conn)

   rank       customer_name      segment   region    revenue    profit
0     1     Daniel Williams  Home Office     West 113,980.62 13,665.36
1     2   Christopher Moore     Consumer     East 112,892.29 16,348.13
2     3        David Wilson     Consumer     West 108,281.62 12,219.85
3     4         James Moore  Home Office    South 107,263.24 13,903.30
4     5         Betty Jones    Corporate    South  98,538.50 13,288.99
5     6      Matthew Wilson  Home Office  Central  98,382.01 15,941.86
6     7     Robert Anderson  Home Office     East  98,147.82  5,317.28
7     8       Sandra Thomas     Consumer  Central  96,543.49 17,598.45
8     9        Daniel Jones  Home Office  Central  94,316.32 12,271.18
9    10  Christopher Garcia    Corporate     West  92,643.43 10,586.38

### BQ2 - Bottom 10 customers (least revenue)

In [15]:
query = """
WITH cust_rev AS (
    SELECT
        c.customer_name,
        c.segment,
        c.region,
        ROUND(SUM(o.sales),  2) as revenue,
        ROUND(SUM(o.profit), 2) as profit,
        COUNT(DISTINCT o.order_id) as num_orders
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.customer_id
)
SELECT customer_name, segment, region, revenue, profit, num_orders
FROM cust_rev
ORDER BY revenue ASC
LIMIT 10
"""

pd.read_sql(query, conn)

          customer_name      segment   region   revenue   profit  num_orders
0          Betty Taylor  Home Office  Central  9,024.17   686.47          17
1    Christopher Martin    Corporate     East 11,862.47   910.49          11
2          Karen Taylor  Home Office  Central 13,498.38 1,131.31          11
3         Charles Moore     Consumer     East 13,587.12   174.43          14
4         Anthony Davis  Home Office    South 13,770.08 1,255.19          18
5        Jessica Martin    Corporate    South 15,490.56 2,375.76          23
6       Jessica Jackson     Consumer     West 16,413.16 3,305.92          21
7          Betty Harris    Corporate     East 16,796.69 2,334.07          15
8        Michael Harris    Corporate  Central 17,129.94 1,593.54          18
9  Christopher Robinson     Consumer     West 17,838.25 2,124.61          14

### BQ3 - Customers with only one order

In [16]:
query = """
WITH order_counts AS (
    SELECT customer_id, COUNT(DISTINCT order_id) as num_orders
    FROM orders
    GROUP BY customer_id
)
SELECT
    c.customer_name,
    c.segment,
    c.region,
    ROUND(SUM(o.sales), 2) as total_sales
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
WHERE o.customer_id IN (
    SELECT customer_id FROM order_counts WHERE num_orders = 1
)
GROUP BY c.customer_id
ORDER BY total_sales DESC
"""

result = pd.read_sql(query, conn)
print(f"customers with only 1 order: {len(result)}")
result.head(15)

customers with only 1 order: 0

Empty DataFrame
Columns: [customer_name, segment, region, total_sales]
Index: []

### BQ4 - Orders above average sales within their category

In [17]:
query = """
SELECT
    o.order_id,
    c.customer_name,
    p.category,
    p.sub_category,
    ROUND(o.sales, 2) as sales,
    ROUND((
        SELECT AVG(o2.sales)
        FROM orders o2
        JOIN products p2 ON o2.product_id = p2.product_id
        WHERE p2.category = p.category
    ), 2) as category_avg
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
JOIN products  p ON o.product_id  = p.product_id
WHERE o.sales > (
    SELECT AVG(o2.sales)
    FROM orders o2
    JOIN products p2 ON o2.product_id = p2.product_id
    WHERE p2.category = p.category
)
ORDER BY p.category, o.sales DESC
LIMIT 20
"""

pd.read_sql(query, conn)

,order_id,customer_name,category,sub_category,sales,category_avg
0,CA-2021-771038,Mark Davis,Furniture,Tables,"14,721.25","2,130.45"
1,CA-2019-292947,Christopher Wilson,Furniture,Tables,"14,635.77","2,130.45"
2,CA-2021-166246,Margaret Miller,Furniture,Tables,"13,240.08","2,130.45"
3,CA-2021-657776,Thomas Harris,Furniture,Tables,"13,183.60","2,130.45"
4,CA-2021-991961,Jessica Jones,Furniture,Tables,"13,012.70","2,130.45"
5,CA-2022-566973,Ashley Thomas,Furniture,Tables,"12,922.39","2,130.45"
6,CA-2022-732608,Betty Jackson,Furniture,Tables,"12,823.35","2,130.45"
7,CA-2022-373295,Daniel Martin,Furniture,Tables,"12,774.53","2,130.45"
8,CA-2020-239458,Sandra Brown,Furniture,Tables,"12,759.03","2,130.45"
9,CA-2019-386525,Michael Robinson,Furniture,Tables,"12,496.27","2,130.45"
10,CA-2020-128282,Robert Anderson,Furniture,Tables,"12,441.17","2,130.45"
11,CA-2020-289724,Daniel Martin,Furniture,Tables,"12,231.28","2,130.45"
12,CA-2019-152240,Daniel Martinez,Furniture,Tables,"12,075.72","2,130.45"
13,CA-2022-614511,David Smith,Furniture,Tables,"12,005.86","2,130.45"
14,CA-2019-285289,Linda Williams,Furniture,Tables,"11,939.59","2,130.45"
15,CA-2019-425587,Susan Wilson,Furniture,Tables,"11,889.12","2,130.45"
16,CA-2022-178404,Matthew Jones,Furniture,Tables,"11,712.84","2,130.45"
17,CA-2021-422866,Jennifer Miller,Furniture,Tables,"11,712.42","2,130.45"
18,CA-2019-631704,David Taylor,Furniture,Tables,"11,628.77","2,130.45"
19,CA-2019-689964,John Martinez,Furniture,Tables,"11,583.23","2,130.45"

### BQ5 - Region-wise sales summary

In [18]:
query = """
WITH region_stats AS (
    SELECT
        c.region,
        ROUND(SUM(o.sales),  2) as total_sales,
        ROUND(SUM(o.profit), 2) as total_profit,
        COUNT(DISTINCT o.order_id)      as total_orders,
        COUNT(DISTINCT o.customer_id)   as unique_customers,
        ROUND(SUM(o.profit) * 100.0 / SUM(o.sales), 2) as margin_pct
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    GROUP BY c.region
)
SELECT
    RANK() OVER (ORDER BY total_sales DESC) as rank,
    region, total_sales, total_profit, total_orders, unique_customers, margin_pct
FROM region_stats
ORDER BY rank
"""

pd.read_sql(query, conn)

,rank,region,total_sales,total_profit,total_orders,unique_customers,margin_pct
0,1,South,"5,946,415.53","762,774.02",2809,120,12.83
1,2,Central,"5,444,587.17","733,610.87",2525,116,13.47
2,3,East,"5,009,062.97","618,322.14",2333,103,12.34
3,4,West,"4,828,245.30","617,994.98",2249,99,12.80

## Insights

In [19]:
top_cust = pd.read_sql("""
    SELECT c.customer_name, ROUND(SUM(o.sales),2) as ts
    FROM orders o JOIN customers c ON o.customer_id=c.customer_id
    GROUP BY c.customer_id ORDER BY ts DESC LIMIT 1
""", conn)

top_region = pd.read_sql("""
    SELECT c.region, ROUND(SUM(o.sales),2) as ts
    FROM orders o JOIN customers c ON o.customer_id=c.customer_id
    GROUP BY c.region ORDER BY ts DESC LIMIT 1
""", conn)

top_cat = pd.read_sql("""
    SELECT p.category, ROUND(SUM(o.profit),2) as tp
    FROM orders o JOIN products p ON o.product_id=p.product_id
    GROUP BY p.category ORDER BY tp DESC LIMIT 1
""", conn)

print("Key findings from the analysis:")
print()
print(f"- Top customer by revenue: {top_cust.iloc[0]['customer_name']} (${top_cust.iloc[0]['ts']:,.2f})")
print(f"- Highest sales region: {top_region.iloc[0]['region']} (${top_region.iloc[0]['ts']:,.2f})")
print(f"- Most profitable category: {top_cat.iloc[0]['category']} (${top_cat.iloc[0]['tp']:,.2f} profit)")
print()
print("Subqueries were used to filter rows against aggregated values like average sales.")
print("CTEs helped break down multi-step aggregations into readable blocks.")
print("Window functions allowed ranking without losing row-level detail.")

Key findings from the analysis:

- Top customer by revenue: Daniel Williams ($113,980.62)
- Highest sales region: South ($5,946,415.53)
- Most profitable category: Technology ($1,811,432.75 profit)

Subqueries were used to filter rows against aggregated values like average sales.
CTEs helped break down multi-step aggregations into readable blocks.
Window functions allowed ranking without losing row-level detail.

In [20]:
conn.close()